import esbuild from 'esbuild';
import process from 'process';
import nodeBuiltins from './esbuild-node-builtins.mjs';
import { watch } from 'fs';
import copyFilesPlugin from './esbuild-copy-files.mjs';
import { obsidianExportPath } from './env.mjs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const buildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/closebrackets',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/comment',
    '@codemirror/fold',
    '@codemirror/gutter',
    '@codemirror/highlight',
    '@codemirror/history',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/matchbrackets',
    '@codemirror/panel',
    '@codemirror/rangeset',
    '@codemirror/rectangular-selection',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/stream-parser',
    '@codemirror/text',
    '@codemirror/tooltip',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...nodeBuiltins,
  ],
  format: 'cjs',
  target: 'es2016',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  plugins: [
    copyFilesPlugin({
      // Only copy styles.css since main.js is already in place
      // and manifest.json should never be overwritten
      './src/styles.css': './styles.css',
    }),
  ],
};

if (prod) {
  esbuild.build(buildOptions).catch(() => process.exit(1));
} else {
  (async () => {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();

    console.log('Watching for changes...');

    watch('./src', { recursive: true }, async (eventType, filename) => {
      if (filename && filename.endsWith('.css') && eventType === 'change') {
        await ctx.rebuild();
      }
    });
  })().catch(() => process.exit(1));
}
